if match case is null for querystring then use default value set to l…
BentleySystems/mapserver pull request #11
Opened 2018-06-26 06:23 UTC by sandiphudekar

if match case is null for querystring then use default value set to layer metadata

2018-06-26 14:02 UTC, danleydmello commented on mapwfs.c
> +  papszWFSDefaultMatchCase = (char**)calloc(sizeof(char*), map->numlayers);
I don't see this memory being freed anywhere. This should be free in erroneous situations as well.

2018-06-26 14:14 UTC, danleydmello requested changes
Most of the code looks good except the one with memory being not release

2018-06-26 14:16 UTC, simen-wu commented on mapogcfilter.c
> +FilterEncodingNode *FLTParseFilterEncoding(const char *szXMLString,const char *defaultMatchCase)
Update the comment of this function since you add a new parameter.

2018-06-26 14:25 UTC, simen-wu commented on mapogcfilter.c
> +		  if (pszTmp == NULL)
Align this following block of code.

2018-06-26 14:26 UTC, simen-wu commented on mapogcfilter.c
> +
Align this block of code. Also put the '{' on the same line of 'if' like others.

2018-06-26 14:40 UTC, simen-wu commented on mapwfs.c
> +  char* papszWFSDefaultMatchCase = NULL;
Use name papszWFSDefaultMatchCases so it looks the same as others (e.g. pszGMLGroups, pszGMLIncludeItems etc.)

2018-06-26 14:42 UTC, simen-wu reviewed
Looks good. Just a few minor things regarding the code formatting and the memory issue as Danley mentioned.

2018-06-27 13:32 UTC, danleydmello approved these changes
Looks good

2018-06-27 16:01 UTC, simen-wu approved these changes
looks good.

2018-06-28 18:10 UTC, merged